In [ ]:
import os
import logging

In [ ]:
logging_str = "[%(asctime)s : %(levelname)s : %(module)s] : %(message)s"
log_dir = "logs"
os.makedirs(log_dir, exist_ok= True)
logging.basicConfig(filename = os.path.join(log_dir,"running_logs.log"),level = logging.INFO , format = logging_str )

In [ ]:
logging.info("check - Info message is being loaded")
logging.error("check - Error message is being loaded")
logging.warning("check - warning")

In [ ]:
import numpy as np

**1.Write a Python Program to Add Two Matrices?**



In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])   # 3*3 matrix
print(x)
y = np.array([[11,22,33],[44,55,66],[77,88,99]])  # 3*3 matrix
print(y)

result = np.array([[0,0,0],[0,0,0],[0,0,0]])


for i in range(len(x)):
  for j in range (len(x[0])):
    result[i][j] = x[i][j] + y[i][j]

print(f"The matrix addition of a and b is{result}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]
The matrix addition of a and b is[[ 12  24  36]
 [ 48  60  72]
 [ 84  96 108]]


**2.Write a Python Program to Multiply Two Matrices?**


In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
y = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(b)

result = np.array([[0,0,0,0],[0,0,0,0],[0,0,0,0]])

for i in range(len(x)):
  for j in range(len(y[0])):
    for k in range(len(y)):
      result[i][j] = x[i][k] * y[k][j]

print(result)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[ 93  96  99 102]
 [186 192 198 204]
 [279 288 297 306]]


**3.Write a Python Program to Transpose a Matrix?**


In [ ]:
x =  np.array([[1,2,3],[4,5,6]])
print(x)

result = np.array([[0,0],[0,0],[0,0]])
print(result)

for i in range(len(x)):
  for j in range(len(x[0])) :
    result[j][i] = x[i][j]

print(result)


[[1 2 3]
 [4 5 6]]
[[0 0]
 [0 0]
 [0 0]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

**4.Write a Python Program to Sort Words in Alphabetic Order?**


In [ ]:
my_str = "Hello this Is an Example With cased letters"

words = [word.lower() for word in my_str.split()]

words.sort()

for word in words:
   print(word)

an
cased
example
hello
is
letters
this
with


**5.Write a Python Program to Remove Punctuation From a String?**

In [ ]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

my_str = "Hello!!!, he said ---and went."

no_punct = ""

for i in my_str:
  if i not in punctuations:
    no_punct = no_punct + i
    

print(no_punct)

Hello he said and went
