In [1]:
import os
import logging

In [3]:
logging_str = "[%(asctime)s : %(levelname)s: %(module)s]: %(message)s"
log_dir = "logs"
os.makedirs(log_dir, exist_ok = True)
logging.basicConfig(filename = os.path.join(log_dir, "running_logs.log"), level = logging.INFO, format = logging_str,
                   filemode = "a")

In [4]:
logging.info("check - Info message is being loaded")
logging.error("check - Error message is being loaded")
logging.warning("check - Warning!")

In [6]:
import numpy as np

### 1.	Write a Python Program to find sum of array?

In [17]:
logging.info(" This is function to find the sum of the array")
def find_sum(arr):
    try :
        sum = 0
        for i in arr:
            sum = sum + i
        return sum
    
    except Exception as e:
        print(f"There is error in this code {e}")
        logging.error("There is error in this code")
    
    else :
        print("This code can be excecuted")
        
        
    
    

In [18]:
logging.info("Exceuting the sum of the array function")
find_sum([1,2,3,4])

10

### 2.	Write a Python Program to find largest element in an array?

In [4]:
a = np.array([1,2,3,4,5])
a.max()

5

### 3.	Write a Python Program for array rotation?

In [11]:
z = np.array([[1,2,3,4],[5,6,7,8]])
print(z)
print("This is array rotaion")
print(z.T)

[[1 2 3 4]
 [5 6 7 8]]
This is array rotaion
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


### 4.	Write a Python Program to Split the array and add the first part to the end?

In [9]:
def SplitArray(arr, n, k):
    for i in range(0, k):
        x = arr[0]
        for j in range(0, n-1):
            arr[j] = arr[j + 1]

        arr[n-1] = x
arr = [15, 40, 15, 16, 50, 36]
n = len(arr)
position = 2
SplitArray(arr, n, position)
for i in range(0, n):
    print(arr[i], end = ' ')

15 16 50 36 15 40 

### 5.	Write a Python Program to check if given array is Monotonic?

__If either array monotonously increasing or monotonously decreasing is known as Monotonic__

In [4]:
def isMonotonic(A):
    return (all(A[i] <= A[i + 1] for i in range(len(A) - 1)) or
      all(A[i] >= A[i + 1] for i in range(len(A) - 1)))

A = [1,2,3,4,5,6,7,8]
print(isMonotonic(A))

True
